Added MLP Mixer Model
unifyai/models pull request #45
Opened 2023-07-21 17:33 UTC by shireenchand

Added the mlpmixer.py file which consists of the model as well as loading the weights from hugging face

2023-07-21 17:39 UTC, shireenchand commented
Hi @juliagsy, can you please review this PR 
Thanks!

2023-07-24 03:40 UTC, juliagsy requested changes
Hey shireen! Thanks for the great work! I've left some comment related to refactor and model loading below, please feel free to lmk if you've any questions, and please request another review when it's done, thanks!

2023-07-24 03:40 UTC, juliagsy commented on ivy_models/mlpmixer/mlpmixer.py
> +class MLPMixer(ivy.Module):
please extend this from `BaseModel`
ref: `ivy_models/base` folder

2023-07-24 03:40 UTC, juliagsy commented on ivy_models/mlpmixer/mlpmixer.py
> +        self,
there's some general conventions to follow, more info in this guide! 
ref: https://docs.google.com/document/d/1NfVngAQlQQlxLGEg47O2lnfn60M5xZekZFei9k5RJd8/edit?usp=sharing

2023-07-24 03:40 UTC, juliagsy commented on ivy_models/mlpmixer/mlpmixer.py
> +        weights = joblib.load(hf_hub_download(repo_id=REPO_ID, filename=FILENAME))
once the `BaseModel` class is inherited, we have a built-in load method, where you can use `MLPMixer.load_from_huggingface(repo_id)` and it'll return the loaded model object, so it'll be something like 
```
if pretrained:
    return MLPMixer.load_from_huggingface(repo_id)
return model = MLPMixer(
         vol,
         inp_dim,
         num_classes=num_classes,
         num_blocks=num_blocks,
         patch_size=patch_size,
         hidden_dim=hidden_dim,
         token_mlp_dim=token_mlp_dim,
         channel_mlp_dim=channel_mlp_dim,
     )
```

2023-07-24 03:40 UTC, juliagsy commented on ivy_models/mlpmixer/mlpmixer.py
> +from huggingface_hub import hf_hub_download
this import will not be needed after the refactor

2023-07-24 03:40 UTC, juliagsy commented on ivy_models/mlpmixer/mlpmixer.py
> +import joblib
this import will not be needed after the refactor

2023-07-25 04:12 UTC, juliagsy requested changes
Hey shireen! Thanks again for the changes! They look great and just a few more points to address before we merge it!
Btw, I think the tests are missing, will you be working on it in another pr just to make sure? Thanks!

2023-07-25 04:12 UTC, juliagsy commented on ivy_models/mlpmixer/mlpmixer.py
> +        self.num_blocks = num_blocks
as we have the spec above, the individual attributes shouldn't be needed

2023-07-25 04:12 UTC, juliagsy commented on ivy_models/mlpmixer/mlpmixer.py
> +            self.inp_dim,
it should then be something like `self.spec.inp_dim` here

2023-07-25 04:12 UTC, juliagsy commented on ivy_models/mlpmixer/mlpmixer.py
> +        x = self.conv(x)
(please double check but) as we would like to support dual format, I think there should be an additional check here, something like, 
```
def _forward(self, x, data_format=None):
        data_format = data_format if data_format else self.spec.data_format
        if data_format == "NHWC":
            x = ivy.permute_dims(x, (0, 3, 1, 2))
        .....
```
please ref alexnet model for more details!

2023-07-25 04:12 UTC, juliagsy commented on ivy_models/mlpmixer/mlpmixer.py
> +            repo_id="unifyai/MLPMixer", weights_path="weights.hdf5"
I've briefly gone through the hf repo, and I think the `config.json` is missing, the required files will be uploaded if the method `push_to_huggingface` is used when uploading the trained model, could you please reupload with that? thanks a lot!

2023-07-25 14:43 UTC, shireenchand commented
Hi @juliagsy, I have made the changes as well as added the config.json file. I'll be adding the test file in another PR.
Do let me know if there are any more changes!

2023-07-26 06:34 UTC, juliagsy requested changes
Hello shireen! the changes look great! there are some (final I'd say) changes required for clean up and optimisation, thanks a lot!

2023-07-26 06:34 UTC, juliagsy commented on ivy_models/mlpmixer/mlpmixer.py
> +class MLPBlock(BaseModel):
sorry, might be a misunderstanding here, only the main model class needs to be inherited from `BaseModel`, the other should just be `ivy.Module`

2023-07-26 06:34 UTC, juliagsy commented on ivy_models/mlpmixer/mlpmixer.py
> +class MixerBlock(BaseModel):
sorry, might be a misunderstanding here, only the main model class needs to be inherited from `BaseModel`, the other should just be `ivy.Module`

2023-07-26 06:34 UTC, juliagsy commented on ivy_models/mlpmixer/mlpmixer.py
> +class MLPMixer(BaseModel):
only this should be `BaseModel`

2023-07-26 06:34 UTC, juliagsy commented on ivy_models/mlpmixer/mlpmixer.py
> +        # x = self.dropout(x)
there's some debugging code or comment I supposed? Please clean up the unnecessary ones, thanks!

2023-07-26 06:34 UTC, juliagsy commented on ivy_models/mlpmixer/mlpmixer.py
> +    if pretrained:
for optimisation purposes, please move this as the first statement or block as a model doesn't need to be created in advance if `retrained=True`

2023-07-28 03:15 UTC, juliagsy approved these changes
Thanks a lot for the changes! lgtm!

2023-08-01 02:58 UTC, merged