Added InceptionNet_v3 Model
unifyai/models pull request #80
Opened 2023-08-22 15:26 UTC by Sarvesh-Kesharwani

2023-08-24 16:58 UTC, juliagsy requested changes
Hey! Thanks for the great work! Just some small formatting and refactoring related changes needed, please let me know when it's done, thanks!

2023-08-24 16:58 UTC, juliagsy commented on ivy_models/inceptionnet/inceptionnet.py
> +    if any([kc in old_key for kc in W_KEY]):
this can be simplified further as there's only one in the `W_KEY` list

2023-08-24 16:58 UTC, juliagsy commented on ivy_models/inceptionnet/inceptionnet.py
> +def inceptionNet_v3(pretrained=True, num_classes=1000, dropout=0.5, data_format="NCHW"):
dropout may be needed as 0 for test

2023-08-24 16:58 UTC, juliagsy commented on ivy_models_tests/inceptionnet/test_inceptionnet.py
> +@pytest.mark.parametrize("load_weights", [False, True])
could you please try the new test format (your existing googlenet should be a good ref), thanks!

2023-08-25 08:51 UTC, Sarvesh-Kesharwani commented on ivy_models/inceptionnet/inceptionnet.py
> +def inceptionNet_v3(pretrained=True, num_classes=1000, dropout=0.5, data_format="NCHW"):
Done.

2023-08-29 08:36 UTC, Sarvesh-Kesharwani commented
> Hey! Thanks for the great work! Just some small formatting and refactoring related changes needed, please let me know when it's done, thanks!

Hey @juliagsy, i implemented all your reviewed comments, i have tried to keep everything as expected this time.
thanks

2023-09-01 10:22 UTC, juliagsy approved these changes
lgtm, thanks a lot for the great work!

2023-09-04 09:17 UTC, juliagsy approved these changes
lgtm, thanks for the changes!

2023-09-04 12:20 UTC, merged